Support Object.toJSON() method
sindresorhus/serialize-error pull request #38
Opened 2020-12-03 15:10 UTC by misozask

2020-12-03 16:23 UTC, misozask commented
Solves following issues: https://github.com/sindresorhus/serialize-error/issues/20 https://github.com/sindresorhus/serialize-error/issues/34

2020-12-03 23:27 UTC, tjconcept commented
What could be reasons for opting out of this functionality?

Apart from the annoyance of a new major version, I'd prefer it to be the default behavior, but it's probably for @sindresorhus to weigh in on.

2020-12-03 23:33 UTC, tjconcept commented on readme.md
> +Example:
Although these examples are technically correct, I'd say they should use Error instances, as anything else is out of scope for this package, and probably falls into "undefined behavior" territory.

2020-12-03 23:36 UTC, tjconcept commented on readme.md
> +    foo: 'bar',
Consider throwing in a rainbow, unicorn, heart or lightning here to increase the consistency, or just to appease @sindresorhus 😉

2020-12-04 11:05 UTC, misozask commented
> I'd prefer it to be the default behavior

It could be a breaking change for someone relying on `Date` to be serialized as `{}`

2020-12-05 00:42 UTC, tjconcept commented
> It could be a breaking change for someone relying on `Date` to be serialized as `{}`

Hence the annoyance of a new major version 🙂

2020-12-25 03:53 UTC, sindresorhus commented
Yeah, I prefer a major version too.

2021-01-01 08:38 UTC, sindresorhus requested changes

2021-01-01 08:38 UTC, sindresorhus commented on index.js
> +const called = Symbol('.toJSON called');
```suggestion
const isCalled = Symbol('.toJSON called');
```

2021-01-01 08:38 UTC, sindresorhus commented on index.d.ts
> +        this.date = new Date(0)
```suggestion
        this.date = new Date()
```

2021-01-01 08:38 UTC, sindresorhus commented on readme.md
> +If the input object contains `.toJSON()` then its result will be returned instead of object properties.
```suggestion
If the input object has a `.toJSON()` method, then it's called instead of serializing the object's properties.
```

2021-01-01 08:38 UTC, sindresorhus commented on readme.md
> +```
index.d.ts should be in sync with the readme.

2021-01-01 08:38 UTC, sindresorhus commented on readme.md
> +const err = new ErrorWithToJSON();
```suggestion
const error = new ErrorWithToJSON();
```

2021-01-01 08:38 UTC, sindresorhus commented on readme.md
> +        this.date = new Date(0);
```suggestion
        this.date = new Date();
```

2021-01-01 08:38 UTC, sindresorhus commented on readme.md
> +        this.date = new Date(0)
```suggestion
        this.date = new Date();
```

2021-01-01 08:38 UTC, sindresorhus commented on readme.md
> +        super()
Use semi-colons everywhere.

2021-01-01 08:38 UTC, sindresorhus commented on test.js
> +	const err = new CustomError();
```suggestion
	const error = new CustomError();
```

2021-01-01 08:38 UTC, sindresorhus commented on test.js
> +	t.true(stack !== undefined);
Use `t.not`

2021-01-01 08:38 UTC, sindresorhus commented on test.js
> +	t.true(stack !== undefined);
Use `t.not`.

2021-01-07 08:19 UTC, sindresorhus commented on index.d.ts
> +It's up on `.toJSON()` implementation to handle circular references and enumerability of the properties.
Typo

2021-01-08 16:53 UTC, merged

2021-01-09 00:41 UTC, moltar commented
Thanks @misozask!